em_management/urls.py
from django.shortcuts import redirect
from django.urls import include, path
from admins.admin import admin_site
from . import views
from django.contrib.auth.views import (LoginView, LogoutView)


urlpatterns = [
    path('login/', LoginView.as_view(
        template_name='login.html',redirect_authenticated_user=True),name='login'),
    path('logout/',LogoutView.as_view(next_page='/login/'),name="logout"),
    path('home/', include('home.urls', namespace="home")),
    path('employees/', include('employees.urls', namespace="employees")),
    path('departments/', include('departments.urls', namespace="departments")),
    path('admins/', include('admins.urls', namespace="admins")),
    path('salaries/', include('salaries.urls', namespace="salaries")),
    path('', include("django.contrib.auth.urls")), 
    path('permission_error/', views.permission_error, name='permission_error'),
    path('', lambda request: redirect('/login/'), name='index'),
]

handler404="handle_error.views.handle_404"
handler500="handle_error.views.handle_500"

employees/urls.py
from django.urls import path, include
from . import views
app_name = 'employees'

urlpatterns = [
    path('list/', views.showEmployeesList, name='list'),
    path('detail/<int:id>/', views.getDetailOfEmployee, name='detail'),
    path('add/',views.showEmployeeForm, name ='add'),
    path('edit/<int:id>/', views.showEmployeeForm, name='edit'),
    path('delete/<int:id>/', views.deleteEmployee, name='delete'),
    path('save/',views.saveEmployee, name ='save'),
    path('checkDuplicate/',views.checkDuplicateEmailAndPhone, name ='checkDuplicate')
]

home/urls.py
from django.urls import path, include
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.showHome, name="home"),
]

employees/models.py
from django.db import models
from salaries.models import Level_Salary
from departments.models import Department
class Employee(models.Model):
    firstName = models.CharField(max_length=45)
    lastName = models.CharField(max_length=45)
    phone = models.CharField(max_length=45)
    email = models.CharField(max_length=45)
    birthday = models.DateField()
    address = models.CharField(max_length=500)
    gender = models.BooleanField()
    image = models.FileField()
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True)
    salary = models.ForeignKey(Level_Salary, on_delete=models.SET_NULL, null=True)
    class Meta:
        db_table = "employees"
    

employees/views.py
import math
from django.shortcuts import render
from django.http import JsonResponse
from salaries.models import Level_Salary
from employees.models import Employee
from departments.models import Department
from django.db.models import Q
from django.shortcuts import redirect
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
import json
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test

@login_required
def showEmployeesList(request):
    per_page = 7
    keyword = request.GET.get('keyword')
    sort = request.GET.get('sort')
    page_num = int(request.GET.get('page', 1))
    sortField = request.GET.get('sortField')
    if not keyword:
        keyword = ""
    if not sort:
        sort = "asc"
    reverseSortField = "desc" if sort == "asc" else "asc"
    if not sortField:
        sortField = "lastName"
    employees = Employee.objects.all()
    if keyword:
        # | Q(lastName=keyword) | %like Q(phone=keyword) | Q(email=keyword) | Q(birthday=keyword) | Q(address=keyword) | Q(department=keyword) | Q(salary=keyword)
        employees = employees.filter(Q(firstName__icontains=keyword) | Q(lastName__icontains=keyword) | Q(phone__icontains=keyword) | Q(
            email__icontains=keyword) | Q(address__icontains=keyword) | Q(department__name__icontains=keyword))
    if sort == "asc" and sortField:
        employees = employees.order_by(sortField)
    if sort == "desc" and sortField:
        employees = employees.order_by('-'+sortField)
    total = employees.count()
    start = (page_num - 1) * per_page
    end = page_num * per_page
    if end > total:
        end = total
    totalPage = math.ceil(total / per_page)
    employees = employees[start: end]

    context = {
        'employees': employees,
        'total': total,
        'start': start,
        'end': end,
        'totalPage': totalPage,
        'range': range(1, totalPage+1),
        'keyword': keyword,
        'pageNum': page_num,
        'sort': sort,
        'sortField': sortField,
        "reverseSortField": reverseSortField
    }
    return render(request, "employees.html", context)

@login_required
def getDetailOfEmployee(request, id):
    employee = Employee.objects.get(pk=id)
    json = {
        'name': employee.firstName + ' ' + employee.lastName,
        'email': employee.email,
        'birthday': employee.birthday,
        'address': employee.address,
        'gender': employee.gender,
        'phone': employee.phone,
        'image': str(employee.image),
        'department': employee.department.name if employee.department else "None",
        'salary': employee.salary.basicSalary if employee.salary else "None"
    }
    return JsonResponse({'data': json}, safe=False)

@login_required
@user_passes_test(lambda u: u.is_superuser, login_url='permission_error')
def showEmployeeForm(request, id=0):
    if id == 0:
        employee = Employee()
        title = 'Add'
    else:
        employee = Employee.objects.get(pk=id)
        title = 'Update'
    departments = Department.objects.all().order_by('name')
    salaries = Level_Salary.objects.all().order_by('basicSalary')
    context = {
        'employee': employee,
        'departments': departments,
        'salaries': salaries,
        'title': title,
        'id': id
    }
    return render(request, "employee_form.html", context)

@login_required
@user_passes_test(lambda u: u.is_superuser, login_url='permission_error')
def saveEmployee(request):
    if request.method == "POST":
        id = int(request.POST.get('id'))
        firstName = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        email = request.POST.get('email')
        birthday = request.POST.get('birthday')
        address = request.POST.get('address')
        gender = request.POST.get('gender')
        gender = True if gender == '1' else False
        phone = request.POST.get('phone')
        image_file = request.FILES.get('image')
        id_department = int(request.POST.get('id_department'))
        id_salary = int(request.POST.get('id_salary'))
        if image_file:
            with open(f"static/image/avatar/{image_file.name}", 'wb+') as destination:
                for chunk in image_file.chunks():
                    destination.write(chunk)

        if id == 0:
            employee = Employee(firstName=firstName, lastName=lastname, email=email, birthday=birthday, address=address, gender=gender,
                                phone=phone, image=image_file.name if image_file else 'default.jpg', department_id=id_department, salary_id=id_salary)
            employee.save()
            messages.success(request, 'Employee saved successfully.')
        else:
            employee = Employee.objects.get(pk=id)
            employee.firstName = firstName
            employee.lastName = lastname
            employee.email = email
            employee.birthday = birthday
            employee.address = address
            employee.gender = gender
            employee.phone = phone
            employee.department_id = id_department
            employee.salary_id = id_salary
            employee.image = image_file.name if image_file else employee.image
            employee.save()
            messages.success(request, 'Employee edited successfully.')
        return redirect("/employees/list/?keyword="+email)

@login_required
@user_passes_test(lambda u: u.is_superuser, login_url='permission_error')
def deleteEmployee(request, id):
    employee = Employee.objects.get(pk=id)
    employee.delete()
    messages.success(request, 'Employee deleted successfully.')
    return redirect('/employees/list/')

@csrf_exempt
def checkDuplicateEmailAndPhone(request):
    if request.method == 'POST':
        payload = request.body.decode('utf-8')
        data = json.loads(payload)
        id = int(data['id'])
        email = data['email']
        phone = data['phone']
        if id == 0:
            if Employee.objects.filter(email=email).exists() | Employee.objects.filter(phone=phone).exists():
                response = "Duplicated"
            else:
                response = "Ok"
        else:
            if Employee.objects.filter(email=email).exclude(id=id).exists() | Employee.objects.filter(phone=phone).exclude(id=id).exists():
                response = "Duplicated"
            else:
                response = "Ok"
        return JsonResponse(response, safe=False)

employees/templates/employee_form.html
{% extends 'index.html' %} {% load static %}  {% block content %}
<div class="table-responsive">
<div class="table-wrapper">
    <div class="table-header">
        <div class="table-title">
          <p>Manage</p>
          <i class="fa-solid fa-circle"></i>
          <a
            href="{% url 'employees:list' %}"
            style="text-decoration: none !important"
            ><p class="text">Employee</p></a
          >
        </div>
        <div class="username_container">
            <div class="username">
              <p>{{ user.get_full_name }}</p><br>
              <i class="fa-solid fa-circle-user"></i>
            </div>
            <p>{{ user.get_type }}</p>
          </div>
      </div>
        <form name="employee_form" class="form"
              method="post" action="/employees/save/"
              style="max-width: 700px; margin: 3rem auto 0"
              enctype="multipart/form-data"
              onsubmit="return checkDuplicate(this);"
        >
            {% csrf_token %}
            <input type="hidden" name ="id" value="{{id}}" id = "id">
            <label for="firstname" class="label-input">
                <span class="input-span">Firstname</span>
                <div class="input-container">
                    <i class="ph-envelope"></i>
                    <input
                            type="text"
                            name="firstname"
                            id="firstname"
                            class="input"
                            placeholder="Enter your firstname"
                            value="{{employee.firstName}}"
                            autofocus
                            required

                    />
                </div>
            </label>
            <label for="lastname" class="label-input">
                <span class="input-span">Lastname</span>
                <div class="input-container">
                    <i class="ph-envelope"></i>
                    <input
                            type="text"
                            name="lastname"
                            id="lastname"
                            class="input"
                            placeholder="Enter your lastname"
                            value="{{employee.lastName}}"
                            autofocus
                            required
                    />
                </div>
            </label>
            <label for="email" class="label-input">
                <span class="input-span">Email</span>
                <div class="input-container">
                    <i class="ph-envelope"></i>
                    <input
                            type="email"
                            name="email"
                            id="email"
                            class="input"
                            placeholder="Enter your email"
                            value="{{employee.email}}"
                            autofocus
                            required
                    />
                </div>
            </label>
            <label for="birthday" class="label-input">
                <span class="input-span">Birthday</span>
                <div class="input-container">
                    <i class="ph-envelope"></i>
                    <input
                            type="date"
                            name="birthday"
                            id="birthday"
                            class="input"
                            value="{{employee.birthday|date:'Y-m-d' }}"
                            placeholder="Enter your birthday"
                            autofocus
                            required
                    />
                </div>
            </label>
            <label for="address" class="label-input">
                <span class="input-span">Address</span>
                <div class="input-container">
                    <i class="ph-envelope"></i>
                    <input
                            type="text"
                            name="address"
                            id="address"
                            class="input"
                            placeholder="Enter your address"
                            value="{{employee.address}}"
                            autofocus
                            required
                    />
                </div>
            </label>
            <label class="label-input">
                <span class="input-span">Gender</span>
                <div class="input-container">
                    <i class="ph-envelope"></i>
                    <span class="input-span">Male</span>
                    <input type="radio" class="radio-input" name="gender" id="male" value="1" {% if employee.gender %}checked{% endif %}>
                    <span class="input-span">Female</span>
                    <input type="radio" class="radio-input" name="gender" id="female" value="0" {% if not employee.gender%}checked{% endif %}>
                </div>
            </label>
            <label for="phone" class="label-input">
                <span class="input-span">Phone Number</span>
                <div class="input-container">
                    <i class="ph-envelope"></i>
                    <input
                            type="text"
                            name="phone"
                            id="phone"
                            class="input"
                            placeholder="Enter your phone"
                            value="{{employee.phone}}"
                            onkeypress='return event.charCode >= 48 && event.charCode <= 57'
                            autofocus
                            required
                    />
                </div>
            </label>
            <input type="hidden" name="image_name" value="{{employee.image}}">
            <label for="image" class="label-input">
                <span class="input-span">Image</span>
                <div class="input-container">
                    <i class="ph-envelope"></i>
                    <input
                            type="file"
                            name="image"
                            id="image"
                            class="input"
                            placeholder="Enter your image"
                            onchange="previewFile(this);"
                            autofocus
                    />
                    <div class="avatar-form-container text-center">
                        <img
                                src="{% static 'image/avatar/' %}{{ employee.image }}"
                                class="avatar-form"
                                alt="Avatar"
                        {% if not employee.image%}hidden{% endif %}
                        />
                    </div>
                </div>
            </label>
            <label for="department" class="label-input">
                <span class="input-span">Department</span>
                <div class="input-container">
                    <i class="ph-envelope"></i>
                    <select name="id_department" id="department" class="input">
                        {% for department in  departments %}
                        <option value="{{department.id}}" {% if employee.department.id == department.id%}selected{% endif %}>{{department.name}}</option>
                        {% endfor %}
                    </select>
                </div>
            </label>
            <label for="salary" class="label-input">
                <span class="input-span">Basic Salary</span>
                <div class="input-container">
                    <i class="ph-envelope"></i>
                    <select name="id_salary" id="salary" class="input">
                        {% for salary in  salaries %}
                        <option value="{{salary.id}}" {% if employee.salary.id == salary.id%}selected{% endif %}>{{salary.basicSalary}}</option>
                        {% endfor %}
                    </select>
                </div>
            </label>

            <button type="submit" class="btn-submit" style="margin-bottom:16px; margin-top: 0!important; ">Submit</button>
        </form>
    </div>
</div>
<div id="messageModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <form>
                <div class="modal-header bg-primary">
                    <h4 class="modal-title">Duplicated Email or Phone</h4>
                    <button
                            type="button"
                            class="close"
                            data-dismiss="modal"
                            aria-hidden="true"
                    >
                        &times;
                    </button>
                </div>
                <div class="modal-body">
                    <p>Another employee are currently using the email or phone number you have been entered. Please choose another one!</p>
                </div>
                <div class="modal-footer">
                    <input
                            type="button"
                            class="btn btn-default"
                            data-dismiss="modal"
                            value="Ok"
                    />
                </div>
            </form>
        </div>
    </div>
  </div>
</div>
<script>
    function checkDuplicate(form){
        phone = ""+$('#phone').val()
        id = ""+$('#id').val()
        email = ""+$('#email').val()
        $.ajax({
                method : 'POST',
                url: 'http://127.0.0.1:8000/employees/checkDuplicate/',
                data: JSON.stringify({
                    phone: phone,
                    id: id,
                    email: email
                }),
                contentType: 'application/json',
                success: function(response) {
                    if(response == "Ok"){
                        form.submit();
                        return true;
                    }else{
                        $("#messageModal").modal()
                        return false;
                    }
                },
                error: function(xhr, status, error) {
                    alert(status);
                    alert(error);
                }
            });
        return false;
    }
    function previewFile(input) {
        var file = $("input[type=file]").get(0).files[0];
        if(file) {
            var reader = new FileReader();
            reader.onload = function() {
                $(".avatar-form").attr("src", reader.result);
                $(".avatar-form").attr("hidden", false);
            }
            reader.readAsDataURL(file);
        }
    }
</script>
{% endblock content %}

employees/templates/employees.html
{% extends 'index.html' %} {% load static %} {% block content %}
<div class="table-responsive">
  <div class="table-wrapper">
    <div class="table-header">
      <div class="table-title">
        <p>Manage</p>
        <i class="fa-solid fa-circle"></i>
        <a
          href="{% url 'employees:list' %}"
          style="text-decoration: none !important"
          ><p class="text">Employee</p></a
        >
      </div>
      <div class="username_container">
        <div class="username">
          <p>{{ user.get_full_name }}</p><br>
          <i class="fa-solid fa-circle-user"></i>
        </div>
        <p>{{ user.get_type }}</p>
      </div>
    </div>
    <div class="table-control">
      <div class="search">
        <form action="?" method="get">
          <input
            name="keyword"
            type="search"
            class="search-input"
            id="search-input"
            placeholder="Search"
            autocomplete="off"
            value="{{keyword}}"
          />
          <i class="search-icon fa-solid fa-magnifying-glass"></i>
        </form>
      </div>
      {% if user.is_superuser %}
      <div class="add">
        <a href="{% url 'employees:add' %}" class="btn" data-toggle="modal">
          <div class="tooltip">
            <i class="add-icon fa-solid fa-plus"></i>
            <p class="tooltiptext">Add new employee</p>
          </div></a
        >
      </div>
      {% endif %}
    </div>
  </div>
  <table class="table table-striped table-hover table-borderless">
    <thead>
      <tr>
        <th>#</th>
        <th>
          <a
            href="/employees/list/?keyword={{keyword}}&sort={{reverseSortField}}&sortField=lastName"
            >Name <i class="fa fa-sort" aria-hidden="true"></i
          ></a>
        </th>
        <th>
          <a
            href="/employees/list/?keyword={{keyword}}&sort={{reverseSortField}}&sortField=email"
            >Email <i class="fa fa-sort" aria-hidden="true"></i
          ></a>
        </th>
        <th>
          <a
            href="/employees/list/?keyword={{keyword}}&sort={{reverseSortField}}&sortField=phone"
            >Phone <i class="fa fa-sort" aria-hidden="true"></i
          ></a>
        </th>
        <th>
          <a
            href="/employees/list/?keyword={{keyword}}&sort={{reverseSortField}}&sortField=address"
            >Address <i class="fa fa-sort" aria-hidden="true"></i
          ></a>
        </th>
        <th>
          <a
            href="/employees/list/?keyword={{keyword}}&sort={{reverseSortField}}&sortField=department"
            >Department <i class="fa fa-sort" aria-hidden="true"></i
          ></a>
        </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for emp in employees %}
      <tr>
        <td>{{forloop.counter}}</td>
        <td class="td-name">
          <img
            src="{% static 'image/avatar/' %}{{ emp.image }}"
            class="avatar"
            alt="Avatar"
          />
          {{emp.firstName}} {{emp.lastName}}
        </td>
        <td class="td-mail">{{emp.email}}</td>
        <td>{{emp.phone}}</td>
        <td>{{emp.address}}</td>
        <td>{{emp.department}}</td>
        <td class="td-action">
          <a
            href="#"
            id="detail-toggle-link"
            onclick="return fetchEmployeeDetail(`{{emp.id}}`);"
            class="edit"
          >
            <div class="tooltip">
              <i class="info-icon fa-solid fa-circle-info"></i>
              <p class="tooltiptext">Info detail</p>
            </div>
          </a>
          {% if user.is_superuser %}
          <a
            href="/employees/edit/{{emp.id}}/"
            class="edit"
            data-toggle="modal"
          >
            <div class="tooltip">
              <i class="edit-icon fa-solid fa-pen-to-square"></i>
              <p class="tooltiptext">Edit</p>
            </div></a
          >
          <a
            href="/employees/delete/{{emp.id}}/"
            class="delete link-delete"
            data-toggle="modal"
          >
            <div class="tooltip">
              <i class="delete-icon fa-solid fa-trash"></i>
              <p class="tooltiptext">Delete</p>
            </div>
          </a>
          {% endif %}
        </td>
        {% endfor %}
      </tr>
    </tbody>
  </table>
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <div class="alert alert-success text-center" role="alert" id="alert">
      <span id="span-message">{{ message }}</span>
    </div>
    {% endfor %}
  </ul>
  {% endif %} {% if not employees %}
  <h3><p class="text text-center">No matches found.</p></h3>
  {% endif %} {% if totalPage > 1%}
  <ul class="pagination">
    <li class="page-item">
      <a
        class="page-control link-back"
        href="/employees/list/?{% if pageNum == 1 %}page={{ pageNum}}{% else %}page={{pageNum|add:-1 }}{% endif %}&keyword={{keyword}}&sort={{sort}}&sortField={{sortField}}"
      >
        <i class="fa-solid fa-arrow-left-long"></i
      ></a>
    </li>
    {% for i in range %}
    <li class="page-item {% if i == pageNum %}active{% endif %}">
      <a
        href="/employees/list/?page={{i}}&keyword={{keyword}}&sort={{sort}}&sortField={{sortField}}"
        class="page-link"
        >{{i}}</a
      >
    </li>
    {% endfor %}
    <li class="page-item">
      <a
        class="page-control link-next"
        href="/employees/list/?{% if pageNum == totalPage %}page={{ pageNum }}{% else %}page={{pageNum|add:1 }}{% endif %}&keyword={{keyword}}&sort={{sort}}&sortField={{sortField}}"
      >
        <i class="fa-solid fa-arrow-right-long"></i
      ></a>
    </li>
  </ul>
  {% endif %}
</div>
<div id="infoEmployeeModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <form>
        <div class="modal-header">
          <h4 class="modal-title">Infomation Of Employee</h4>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-hidden="true"
          >
            &times
          </button>
        </div>
        {% csrf_token %}
        <div class="modal-body">
          <div class="form-group">
            <label></label>
            <img
              id="image"
              class="avatar"
              alt="Avatar"
              src="{% static 'image/avatar/1.jpg' %}"
            />
          </div>
          <div class="form-group">
            <label>Name: </label>
            <span id="name"></span>
          </div>
          <div class="form-group">
            <label>Email:</label>
            <span id="email"></span>
          </div>
          <div class="form-group">
            <label>Birthday: </label>
            <span id="birthday"></span>
          </div>
          <div class="form-group">
            <label>Address: </label>
            <span id="address"></span>
          </div>
          <div class="form-group">
            <label>Gender: </label>
            <span id="gender"></span>
          </div>
          <div class="form-group">
            <label>Phone: </label>
            <span id="phone"></span>
          </div>
          <div class="form-group">
            <label for="department">Department: </label>
            <span id="department"></span>
          </div>
          <div class="form-group">
            <label for="salary">Salary</label>
            <span id="salary"></span>
          </div>
        </div>
        <div class="modal-footer">
          <input
            type="button"
            class="btn btn-default"
            data-dismiss="modal"
            value="Cancel"
          />
        </div>
      </form>
    </div>
  </div>
</div>
<div id="deleteEmployeeModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <form>
        <div class="modal-header">
          <h4 class="modal-title">Delete Employee</h4>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-hidden="true"
          >
            &times;
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this employee?</p>
          <p class="text-warning">
            <small>This action cannot be undone.</small>
          </p>
        </div>
        <div class="modal-footer">
          <input
            type="button"
            class="btn btn-default"
            data-dismiss="modal"
            value="Cancel"
          />
          <a href="" class="btn btn-danger but-delete">Delete</a>
        </div>
      </form>
    </div>
  </div>
</div>
<script>
  $(".search-icon").click(function () {
    $(this).closest("form").submit();
  });
  function fetchEmployeeDetail(id) {
    var csrf = $("input[name=csrfmiddlewaretoken]").val();
    $.ajax({
      url: "http://127.0.0.1:8000/employees/detail/" + id + "/",
      method: "GET",
      success: function (response) {
        // response = JSON.parse(response)
        let img = response.data.image;
        let img_src = `{% static "image/avatar/img" %}`;
        img_src = img_src.replace("img", img);
        $(`#name`).html(response.data.name);
        $(`#email`).html(response.data.email);
        $(`#birthday`).html(response.data.birthday);
        $(`#address`).html(response.data.address);
        let gender = response.data.gender === true ? "Male" : "Female";
        $(`#gender`).html(gender);
        $(`#phone`).html(response.data.phone);
        $(`#image`).attr("src", img_src);
        $(`#department`).html(response.data.department);
        $(`#salary`).html(response.data.salary);
        $("#infoEmployeeModal").modal();
      },
      error: function (error) {
        console.log(error);
      },
    });
  }
  $(document).ready(function () {
    message = $("#span-message").text();
    console.log(message);
    if (message != "") {
      setTimeout(function () {
        $("#alert").fadeOut();
      }, 2000);
    }
    $(".link-delete").click(function (e) {
      e.preventDefault();
      $("#deleteEmployeeModal").modal();
      $(".but-delete").attr("href", $(this).attr("href"));
    });
  });
</script>
{% endblock content %}