admins/urls.py
from django.urls import path
from . import views
app_name = 'admins'

urlpatterns = [
    path('list/', views.showAdminsList, name='list'),
    path('detail/<int:id>/', views.getDetailOfAdmin, name='detail'),
    path('add/', views.showAdminForm, name='add'),
    path('edit/<int:id>/', views.showAdminForm, name='edit'),
    path('delete/<int:id>/', views.deleteAdmin, name='delete'),
    path('save/', views.saveAdmin, name='save'),
    path('checkDuplicate/', views.checkDuplicateUsernameAndEmployee,
         name='checkDuplicate'),
]

em_management/urls.py
from django.shortcuts import redirect
from django.urls import include, path
from admins.admin import admin_site
from . import views
from django.contrib.auth.views import (LoginView, LogoutView)


urlpatterns = [
    path('login/', LoginView.as_view(
        template_name='login.html',redirect_authenticated_user=True),name='login'),
    path('logout/',LogoutView.as_view(next_page='/login/'),name="logout"),
    path('home/', include('home.urls', namespace="home")),
    path('employees/', include('employees.urls', namespace="employees")),
    path('departments/', include('departments.urls', namespace="departments")),
    path('admins/', include('admins.urls', namespace="admins")),
    path('salaries/', include('salaries.urls', namespace="salaries")),
    path('', include("django.contrib.auth.urls")), 
    path('permission_error/', views.permission_error, name='permission_error'),
    path('', lambda request: redirect('/login/'), name='index'),
]

handler404="handle_error.views.handle_404"
handler500="handle_error.views.handle_500"

home/urls.py
from django.urls import path, include
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.showHome, name="home"),
]

admins/templates/admin_form.html
{% extends 'index.html' %} {% load static %} {% block content %}
<div class="table-responsive">
  <div class="table-wrapper">
    <div class="table-header">
      <div class="table-title">
        <p>Manage</p>
        <i class="fa-solid fa-circle"></i>
        <a
          href="{% url 'admins:list' %}"
          style="text-decoration: none !important"
          ><p class="text">Admin</p></a
        >
      </div>
      <div class="username_container">
        <div class="username">
          <p>{{ user.get_full_name }}</p><br>
          <i class="fa-solid fa-circle-user"></i>
        </div>
        <p>{{ user.get_type }}</p>
      </div>
    </div>
    <form
      name="admin_form"
      class="form"
      method="post"
      action="/admins/save/"
      style="max-width: 700px; margin: 3rem auto 0"
      enctype="multipart/form-data"
      onsubmit="return checkDuplicate(this);"
    >
      {% csrf_token %}
      <div class="input-container">
        <input class="input" type="hidden" name="id" value="{{id}}" id="id" />
        <select class="input" id="employee_id" name="employee_id">
          {% for employee in employees %}
          <option value="{{employee.id}}" {% if admin.employee.id == employee.id%}selected{% endif %}>{{employee.firstName}} {{employee.lastName}} - {{employee.phone}}</option>
          {% endfor %}
        </select>
      </div>
      {% if title != 'Update' %}
      <label for="username" class="label-input">
        <span class="input-span">Username</span>
        <div class="input-container">
          <i class="ph-envelope"></i>
          <input
            type="text"
            name="username"
            id="username"
            class="input"
            placeholder="Enter your username"
            value="{{admin.username}}"
            autofocus
            required
          />
        </div>
      </label>
      {% endif %}
      <label for="password" class="label-input">
        {% if title == 'Update' %}
        <span style="color:#228BE6; font-style: italic; font-weight: 200;">Leave password blank if you don't want to update password</span>
        {% endif %}
        <span class="input-span">Password</span>
        <div class="input-container">
          <i class="ph-envelope"></i>
          <input
            type="password"
            name="password"
            id="password"
            class="input"
            placeholder="Enter your password"
            value=""
            autofocus
            {% if title != 'Update' %}required{% endif %}
          />
        </div>
      </label>
      <label for="is_staff" class="label-input">
        <span class="input-span">Type</span>
        <div class="input-container">
          <i class="ph-envelope"></i>
          <select class="input" id="is_staff" name="is_staff">
            <option value="0" {% if admin.is_staff == 0%}selected{% endif %}>Manager</option>
            <option value="1" {% if admin.is_staff == 1%}selected{% endif %}>Employee</option>
          </select>
        </div>
      </label>
      <button
        type="submit"
        class="btn-submit"
        style="margin-bottom: 16px; margin-top: 0 !important"
      >
        Submit
      </button>
    </form>
  </div>
</div>
<div
  class="modal fade"
  id="messageModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header bg-primary">
        <h5 class="modal-title" id="exampleModalLabel">
          Duplicate information
        </h5>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>
          Another admin is currently using the username or the employee already has an admin account!
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">
          OK
        </button>
      </div>
    </div>
  </div>
</div>
<script>
  function checkDuplicate(form) {
    var employee_id = $("#employee_id").val();
    var id = $("#id").val();
    var username = $("#username").val();
    $.ajax({
      method: "POST",
      url: "http://127.0.0.1:8000/admins/checkDuplicate/",
      data: JSON.stringify({
        employee_id: employee_id,
        id: id,
        username: username,
      }),
      contentType: "application/json",
      success: function (response) {
        if (response == "Ok") {
          form.submit();
        } else {
          $("#messageModal").modal("show");
        }
      },
      error: function (xhr, status, error) {
        alert(status);
        alert(error);
      },
    });
    return false;
  }
</script>
{% endblock content %}

admins/templates/admins.html
{% extends 'index.html' %} {% load static %} {% block content %}
<div class="table-responsive">
  <div class="table-wrapper">
    <div class="table-header">
      <div class="table-title">
        <p>Manage</p>
        <i class="fa-solid fa-circle"></i>
        <a
          href="{% url 'admins:list' %}"
          style="text-decoration: none !important"
          ><p class="text">Admin</p></a
        >
      </div>
      <div class="username_container">
        <div class="username">
          <p>{{ user.get_full_name }}</p>
          <br />
          <i class="fa-solid fa-circle-user"></i>
        </div>
        <p>{{ user.get_type }}</p>
      </div>
    </div>
    <div class="table-control">
      <div class="search">
        <form action="?" method="get">
          <input
            name="keyword"
            type="search"
            class="search-input"
            id="search-input"
            placeholder="Search"
            autocomplete="off"
            value="{{keyword}}"
          />
          <i class="search-icon fa-solid fa-magnifying-glass"></i>
        </form>
      </div>
      {% if user.is_superuser %}
      <div class="add">
        <a href="{% url 'admins:add' %}" class="btn" data-toggle="modal">
          <div class="tooltip">
            <i class="add-icon fa-solid fa-plus"></i>
            <p class="tooltiptext">Add new admin</p>
          </div></a
        >
      </div>
      {% endif %}
    </div>
  </div>
  <table class="table table-striped table-hover table-borderless">
    <thead>
      <tr>
        <th>#</th>
        <th>
          <a
            href="/admins/list/?keyword={{keyword}}&sort={{reverseSortField}}&sortField=lastName"
            >Name <i class="fa fa-sort" aria-hidden="true"></i
          ></a>
        </th>
        <th>
          <a
            href="/admins/list/?keyword={{keyword}}&sort={{reverseSortField}}&sortField=username"
            >Username <i class="fa fa-sort" aria-hidden="true"></i
          ></a>
        </th>
        <th>
          <a
            href="/admins/list/?keyword={{keyword}}&sort={{reverseSortField}}&sortField=gender"
            >Gender <i class="fa fa-sort" aria-hidden="true"></i
          ></a>
        </th>
        <th>
          <a
            href="/admins/list/?keyword={{keyword}}&sort={{reverseSortField}}&sortField=phone"
            >Phone <i class="fa fa-sort" aria-hidden="true"></i
          ></a>
        </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for ad in admins %}
      <tr>
        <td>{{forloop.counter}}</td>
        <td class="td-name">
          {{ad.employee.firstName}} {{ad.employee.lastName}}
        </td>
        <td class="td-username">{{ad.username}}</td>
        <td>{% if ad.employee.gender %} Male {%else %} Female {% endif %}</td>
        <td>{{ad.employee.phone}}</td>
        <td class="td-action">
          <a
            href="#"
            id="detail-toggle-link"
            onclick="return fetchAdminDetail(`{{ad.id}}`);"
            class="edit"
          >
            <div class="tooltip">
              <i class="info-icon fa-solid fa-circle-info"></i>
              <p class="tooltiptext">Info detail</p>
            </div>
          </a>
          {% if user.is_superuser %}
          <a href="/admins/edit/{{ad.id}}/" class="edit" data-toggle="modal">
            <div class="tooltip">
              <i class="edit-icon fa-solid fa-pen-to-square"></i>
              <p class="tooltiptext">Edit</p>
            </div></a
          >
          <a
            href="/admins/delete/{{ad.id}}/"
            class="delete link-delete"
            data-toggle="modal"
          >
            <div class="tooltip">
              <i class="delete-icon fa-solid fa-trash"></i>
              <p class="tooltiptext">Delete</p>
            </div>
          </a>
        </td>
        {% endif %} {% endfor %}
      </tr>
    </tbody>
  </table>
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <div class="alert alert-success top-right" role="alert" id="alert">
      <span id="span-message">{{ message }}</span>
    </div>
    {% endfor %}
  </ul>
  {% endif %} {% if not admins %}
  <h3><p class="text text-center">No matches found.</p></h3>
  {% endif %} {% if totalPage > 1%}
  <ul class="pagination">
    <li class="page-item">
      <a
        class="page-control link-back"
        href="/admins/list/?{% if pageNum == 1 %}page={{ pageNum}}{% else %}page={{pageNum|add:-1 }}{% endif %}&keyword={{keyword}}&sort={{sort}}&sortField={{sortField}}"
      >
        <i class="fa-solid fa-arrow-left-long"></i
      ></a>
    </li>
    {% for i in range %}
    <li class="page-item {% if i == pageNum %}active{% endif %}">
      <a
        href="/admins/list/?page={{i}}&keyword={{keyword}}&sort={{sort}}&sortField={{sortField}}"
        class="page-link"
        >{{i}}</a
      >
    </li>
    {% endfor %}
    <li class="page-item">
      <a
        class="page-control link-next"
        href="/admins/list/?{% if pageNum == totalPage %}page={{ pageNum }}{% else %}page={{pageNum|add:1 }}{% endif %}&keyword={{keyword}}&sort={{sort}}&sortField={{sortField}}"
      >
        <i class="fa-solid fa-arrow-right-long"></i
      ></a>
    </li>
  </ul>
  {% endif %}
</div>
<div id="infoAdminModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <form>
        <div class="modal-header">
          <h4 class="modal-title">Infomation Of Admin</h4>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-hidden="true"
          >
            &times
          </button>
        </div>
        {% csrf_token %}
        <div class="modal-body">
          <div class="form-group">
            <label>Name: </label>
            <span id="name"></span>
          </div>
          <div class="form-group">
            <label>Username:</label>
            <span id="username"></span>
          </div>
          <div class="form-group">
            <label>Email: </label>
            <span id="email"></span>
          </div>
          <div class="form-group">
            <label>Phone: </label>
            <span id="phone"></span>
          </div>
          <div class="form-group">
            <label>Address: </label>
            <span id="address"></span>
          </div>
          <div class="form-group">
            <label>Account type: </label>
            <span id="type"></span>
          </div>
        </div>
        <div class="modal-footer">
          <input
            type="button"
            class="btn btn-default"
            data-dismiss="modal"
            value="Cancel"
          />
        </div>
      </form>
    </div>
  </div>
</div>
<div id="deleteAdminModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <form>
        <div class="modal-header">
          <h4 class="modal-title">Delete Admin</h4>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-hidden="true"
          >
            &times;
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this admin account?</p>
          <p class="text-warning">
            <small>This action cannot be undone.</small>
          </p>
        </div>
        <div class="modal-footer">
          <input
            type="button"
            class="btn btn-default"
            data-dismiss="modal"
            value="Cancel"
          />
          <a href="" class="btn btn-danger but-delete">Delete</a>
        </div>
      </form>
    </div>
  </div>
</div>
<script>
  $(".search-icon").click(function () {
    $(this).closest("form").submit();
  });
  function fetchAdminDetail(id) {
    var csrf = $("input[name=csrfmiddlewaretoken]").val();
    $.ajax({
      url: "http://127.0.0.1:8000/admins/detail/" + id + "/",
      method: "GET",
      success: function (response) {
        $(`#name`).html(response.data.name);
        $(`#username`).html(response.data.username);
        $(`#email`).html(response.data.email);
        $(`#phone`).html(response.data.phone);
        $(`#address`).html(response.data.address);
        $(`#type`).html(response.data.type);
        $("#infoAdminModal").modal();
      },
      error: function (error) {
        console.log(error);
      },
    });
  }
  $(document).ready(function () {
    message = $("#span-message").text();
    console.log(message);
    if (message != "") {
      setTimeout(function () {
        $("#alert").fadeOut();
      }, 2000);
    }
    $(".link-delete").click(function (e) {
      e.preventDefault();
      $("#deleteAdminModal").modal();
      $(".but-delete").attr("href", $(this).attr("href"));
    });
  });
</script>
{% endblock content %}