em_management/urls.py
from django.shortcuts import redirect
from django.urls import include, path
from admins.admin import admin_site
from . import views
from django.contrib.auth.views import (LoginView, LogoutView)


urlpatterns = [
    path('login/', LoginView.as_view(
        template_name='login.html',redirect_authenticated_user=True),name='login'),
    path('logout/',LogoutView.as_view(next_page='/login/'),name="logout"),
    path('home/', include('home.urls', namespace="home")),
    path('employees/', include('employees.urls', namespace="employees")),
    path('departments/', include('departments.urls', namespace="departments")),
    path('admins/', include('admins.urls', namespace="admins")),
    path('salaries/', include('salaries.urls', namespace="salaries")),
    path('', include("django.contrib.auth.urls")), 
    path('permission_error/', views.permission_error, name='permission_error'),
    path('', lambda request: redirect('/login/'), name='index'),
]

handler404="handle_error.views.handle_404"
handler500="handle_error.views.handle_500"

home/urls.py
from django.urls import path, include
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.showHome, name="home"),
]

salaries/urls.py
from django.urls import path
from . import views
app_name = 'salaries'

urlpatterns = [
    path('list/', views.showLevel_SalariesList, name='list'),
    path('detail/<int:id>/', views.getDetailOfLevel_Salary, name='detail'),
    path('add/',views.showLevel_SalaryForm, name ='add'),
    path('edit/<int:id>/', views.showLevel_SalaryForm, name='edit'),
    path('delete/<int:id>/', views.deleteLevel_Salary, name='delete'),
    path('save/',views.saveLevel_Salary, name ='save'),
]

salaries/models.py
from django.db import models
class Level_Salary(models.Model):
    basicSalary = models.FloatField()
    coefficientPay = models.FloatField()
    coefficientAllowance = models.FloatField()
    def __str__(self) -> str:
        return str(self.basicSalary)
    class Meta:
        db_table = "level_salaries"

salaries/views.py
import math
from django.shortcuts import render
from django.http import JsonResponse
from salaries.models import Level_Salary
from django.db.models import Q
from django.shortcuts import redirect
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test


@login_required
def showLevel_SalariesList(request):
    per_page = 8
    keyword = request.GET.get('keyword')
    sort = request.GET.get('sort')
    page_num = int(request.GET.get('page', 1))
    sortField = request.GET.get('sortField')
    if not keyword:
        keyword = ""
    if not sort:
        sort = "asc"
    reverseSortField = "desc" if sort == "asc" else "asc"
    if not sortField:
        sortField = "basicSalary"
    level_salaries = Level_Salary.objects.all()

    for level_salarie in level_salaries:
        level_salarie.basicSalary = str(int(level_salarie.basicSalary))
    if keyword:
        # | Q(lastName=keyword) | %like Q(phone=keyword) | Q(email=keyword) | Q(birthday=keyword) | Q(address=keyword) | Q(department=keyword) | Q(salary=keyword)
        level_salaries = level_salaries.filter(Q(basicSalary__icontains=keyword.split('.')[0]) | Q(
            coefficientPay__icontains=keyword) | Q(coefficientAllowance__icontains=keyword))
    if sort == "asc" and sortField:
        level_salaries = level_salaries.order_by(sortField)
    if sort == "desc" and sortField:
        level_salaries = level_salaries.order_by('-'+sortField)
    total = level_salaries.count()
    start = (page_num - 1) * per_page
    end = page_num * per_page
    if end > total:
        end = total
    totalPage = math.ceil(total / per_page)
    level_salaries = level_salaries[start: end]

    context = {
        'level_salaries': level_salaries,
        'total': total,
        'start': start,
        'end': end,
        'totalPage': totalPage,
        'range': range(1, totalPage+1),
        'keyword': keyword,
        'pageNum': page_num,
        'sort': sort,
        'sortField': sortField,
        "reverseSortField": reverseSortField
    }
    return render(request, "salaries.html", context)


@login_required
def getDetailOfLevel_Salary(request, id):
    level_salary = Level_Salary.objects.get(pk=id)
    json = {
        'basicSalary': level_salary.basicSalary,
        'coefficientPay': level_salary.coefficientPay,
        'coefficientAllowance': level_salary.coefficientAllowance,
    }
    return JsonResponse({'data': json}, safe=False)


@login_required
@user_passes_test(lambda u: u.is_superuser, login_url='permission_error')
def showLevel_SalaryForm(request, id=0):
    if id == 0:
        level_salary = Level_Salary()
        title = 'Add'
    else:
        level_salary = Level_Salary.objects.get(pk=id)
        title = 'Update'

    context = {
        'level_salary': level_salary,
        'id': id,
        'title': title
    }
    return render(request, "salaries_form.html", context)


@login_required
@user_passes_test(lambda u: u.is_superuser, login_url='permission_error')
def saveLevel_Salary(request):
    if request.method == "POST":
        id = int(request.POST.get('id'))
        basicSalary = request.POST.get('basicSalary')
        coefficientPay = request.POST.get('coefficientPay')
        coefficientAllowance = request.POST.get('coefficientAllowance')

        if id == 0:
            salary = Level_Salary(
                basicSalary=basicSalary, coefficientPay=coefficientPay, coefficientAllowance=coefficientAllowance)
            salary.save()
            messages.success(request, 'Salary level saved successfully.')
        else:
            salary = Level_Salary.objects.get(pk=id)
            salary.basicSalary = basicSalary
            salary.coefficientPay = coefficientPay
            salary.coefficientAllowance = coefficientAllowance
            salary.save()
            messages.success(request, 'Salary level edited successfully.')
        # return render(request, "checkform.html", context)
        return redirect("/salaries/list/?keyword=" + basicSalary.split('.')[0])


@login_required
@user_passes_test(lambda u: u.is_superuser, login_url='permission_error')
def deleteLevel_Salary(request, id):
    salary = Level_Salary.objects.get(pk=id)
    salary.delete()
    messages.success(request, 'Salary level deleted successfully.')
    return redirect('/salaries/list/')

salaries/templates/salaries.html
{% extends 'index.html' %} {% load static %} {% block content %}
<div class="table-responsive">
  <div class="table-wrapper">
    <div class="table-header">
      <div class="table-title">
        <p>Manage</p>
        <i class="fa-solid fa-circle"></i>
        <a
          href="{% url 'salaries:list' %}"
          style="text-decoration: none !important"
          ><p class="text">Salary Level</p></a
        >
      </div>
      <div class="username_container">
        <div class="username">
          <p>{{ user.get_full_name }}</p><br>
          <i class="fa-solid fa-circle-user"></i>
        </div>
        <p>{{ user.get_type }}</p>
      </div>
    </div>
    <div class="table-control">
      <div class="search">
        <form action="?" method="get">
          <input
            name="keyword"
            type="search"
            class="search-input"
            id="search-input"
            placeholder="Search"
            autocomplete="off"
            value="{{keyword}}"
          />
          <i class="search-icon fa-solid fa-magnifying-glass"></i>
        </form>
      </div>
      {% if user.is_superuser %}
      <div class="add">
        <a href="{% url 'salaries:add' %}" class="btn" data-toggle="modal">
          <div class="tooltip">
            <i class="add-icon fa-solid fa-plus"></i>
            <p class="tooltiptext">Add new salary level</p>
          </div></a
        >
      </div>
      {% endif %}
    </div>
  </div>
  <table class="table table-striped table-hover table-borderless">
    <thead>
      <tr>
        <th>#</th>
        <th>
          <a
            href="/salaries/list/?keyword={{keyword}}&sort={{reverseSortField}}&sortField=basicSalary"
            >Basic Salary <i class="fa fa-sort" aria-hidden="true"></i
          ></a>
        </th>
        <th>
          <a
            href="/salaries/list/?keyword={{keyword}}&sort={{reverseSortField}}&sortField=coefficientPay"
            >Coefficient Pay <i class="fa fa-sort" aria-hidden="true"></i
          ></a>
        </th>
        <th>
          <a
            href="/salaries/list/?keyword={{keyword}}&sort={{reverseSortField}}&sortField=coefficientAllowance"
          >
            Coefficient Allowance <i class="fa fa-sort" aria-hidden="true"></i
          ></a>
        </th>

        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for sal in level_salaries %}
      <tr>
        <td>{{forloop.counter}}</td>
        <td>{{sal.basicSalary}}</td>
        <td>{{sal.coefficientPay}}</td>
        <td>{{sal.coefficientAllowance}}</td>
        {% if user.is_superuser %}
        <td class="td-action">
          <a href="/salaries/edit/{{sal.id}}/" class="edit" data-toggle="modal">
            <div class="tooltip">
              <i class="edit-icon fa-solid fa-pen-to-square"></i>
              <p class="tooltiptext">Edit</p>
            </div>
          </a>
          <a
            href="/salaries/delete/{{sal.id}}/"
            class="delete link-delete"
            data-toggle="modal"
          >
            <div class="tooltip">
              <i class="delete-icon fa-solid fa-trash"></i>
              <p class="tooltiptext">Delete</p>
            </div>
          </a>
        </td>
        {% else %}
        <td class="td-action"></td>
        {% endif %} {% endfor %}
      </tr>
    </tbody>
  </table>
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <div
      class="alert alert-success text-center fixed-top"
      role="alert"
      id="alert"
    >
      <span id="span-message">{{ message }}</span>
    </div>
    {% endfor %}
  </ul>
  {% endif %} {% if not level_salaries %}
  <h3><p class="text text-center">No matches found.</p></h3>
  {% endif %} {% if totalPage > 1%}
  <ul class="pagination">
    <li class="page-item">
      <a
        class="page-control link-back"
        href="/salaries/list/?{% if pageNum == 1 %}page={{ pageNum}}{% else %}page={{pageNum|add:-1 }}{% endif %}&keyword={{keyword}}&sort={{sort}}&sortField={{sortField}}"
      >
        <i class="fa-solid fa-arrow-left-long"></i
      ></a>
    </li>
    {% for i in range %}
    <li class="page-item {% if i == pageNum %}active{% endif %}">
      <a
        href="/salaries/list/?page={{i}}&keyword={{keyword}}&sort={{sort}}&sortField={{sortField}}"
        class="page-link"
        >{{i}}</a
      >
    </li>
    {% endfor %}
    <li class="page-item">
      <a
        class="page-control link-next"
        href="/salaries/list/?{% if pageNum == totalPage %}page={{ pageNum }}{% else %}page={{pageNum|add:1 }}{% endif %}&keyword={{keyword}}&sort={{sort}}&sortField={{sortField}}"
      >
        <i class="fa-solid fa-arrow-right-long"></i
      ></a>
    </li>
  </ul>
  {% endif %}
</div>
<div id="infoLevel_SalaryModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <form>
        <div class="modal-header">
          <h4 class="modal-title">Infomation Of Level Salary</h4>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-hidden="true"
          >
            &times
          </button>
        </div>
        {% csrf_token %}
        <div class="modal-body">
          <div class="form-group">
            <label>Basic Salary: </label>
            <span id="basicSalary"></span>
          </div>
          <div class="form-group">
            <label>Coefficient Pay:</label>
            <span id="coefficientPay"></span>
          </div>

          <div class="form-group">
            <label>Coefficient Allowance: </label>
            <span id="coefficientAllowance"></span>
          </div>
        </div>
        <div class="modal-footer">
          <input
            type="button"
            class="btn btn-default"
            data-dismiss="modal"
            value="Cancel"
          />
        </div>
      </form>
    </div>
  </div>
</div>
<div id="deleteLevel_SalaryModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <form>
        <div class="modal-header">
          <h4 class="modal-title">Delete Level Salary</h4>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-hidden="true"
          >
            &times;
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this level salary?</p>
          <p class="text-warning">
            <small>This action cannot be undone.</small>
          </p>
        </div>
        <div class="modal-footer">
          <input
            type="button"
            class="btn btn-default"
            data-dismiss="modal"
            value="Cancel"
          />
          <a href="" class="btn btn-danger but-delete">Delete</a>
        </div>
      </form>
    </div>
  </div>
</div>
<script>
  $(".search-icon").click(function () {
    $(this).closest("form").submit();
  });
  function fetchLevel_SalaryDetail(id) {
    var csrf = $("input[name=csrfmiddlewaretoken]").val();
    $.ajax({
      url: "http://127.0.0.1:8000/salaries/detail/" + id + "/",
      method: "GET",
      success: function (response) {
        // response = JSON.parse(response)
        $(`#basicSalary`).html(response.data.basicSalary);
        $(`#coefficientPay`).html(response.data.coefficientPay);
        $(`#coefficientAllowance`).html(response.data.coefficientAllowance);
        $("#infoLevel_SalaryModal").modal();
      },
      error: function (error) {
        console.log(error);
      },
    });
  }
  $(document).ready(function () {
    message = $("#span-message").text();
    console.log(message);
    if (message != "") {
      setTimeout(function () {
        $("#alert").fadeOut();
      }, 2000);
    }
    $(".link-delete").click(function (e) {
      e.preventDefault();
      $("#deleteLevel_SalaryModal").modal();
      $(".but-delete").attr("href", $(this).attr("href"));
    });
  });
</script>
{% endblock content %}

salaries/templates/salaries_form.html
{% extends 'index.html' %} {% load static %}  {% block content %}
<div class="table-responsive">
<div class="table-wrapper">
    <div class="table-header">
        <div class="table-title">
          <p>Manage</p>
          <i class="fa-solid fa-circle"></i>
          <a
            href="{% url 'salaries:list' %}"
            style="text-decoration: none !important"
            ><p class="text">Salary Level</p></a
          >
        </div>
        <div class="username_container">
            <div class="username">
              <p>{{ user.get_full_name }}</p><br>
              <i class="fa-solid fa-circle-user"></i>
            </div>
            <p>{{ user.get_type }}</p>
          </div>
      </div>
    </div>
        <form name="level_salary_form" class="form"
              method="post" action="/salaries/save/"
              style="max-width: 700px; margin: 0 auto"
              enctype="multipart/form-data"
              onsubmit="return formSubmit(this);"
        >
            {% csrf_token %}
            <input type="hidden" name ="id" value="{{id}}" id = "id">
            <label for="basicSalary" class="label-input">
                <span class="input-span">Basic Salary</span>
                <div class="input-container">
                    <i class="ph-envelope"></i>
                    <input
                            type="text"
                            name="basicSalary"
                            id="basicSalary"
                            class="input"
                            placeholder="Enter your Basic Salary"
                            value="{{level_salary.basicSalary}}"
                            onkeypress='return event.charCode >= 48 && event.charCode <= 57'
                            autofocus
                            required
                    />
                </div>
            </label>
            <label for="coefficientPay" class="label-input">
                <span class="input-span">Coefficient Pay</span>
                <div class="input-container">
                    <i class="ph-envelope"></i>
                    <input
                            input type="number" min="0" max="5" step="0.1"
                            name="coefficientPay"
                            id="coefficientPay"
                            class="input"
                            placeholder="Enter your Coefficient Pay"
                            value="{{level_salary.coefficientPay}}"
                            onkeypress='return event.charCode >= 48 && event.charCode <= 57'
                            autofocus
                            required
                    />
                </div>
            </label>
            <label for="coefficientAllowance" class="label-input">
                <span class="input-span">Coefficient Allowance</span>
                <div class="input-container">
                    <i class="ph-envelope"></i>
                    <input

                            input type="number" min="0" max="5" step="0.1"
                            name="coefficientAllowance"
                            id="coefficientAllowance"
                            class="input"
                            placeholder="Enter your Coefficient Allowance"
                            value="{{level_salary.coefficientAllowance}}"
                            onkeypress='return event.charCode >= 48 && event.charCode <= 57'
                            autofocus
                            required
                    />
                </div>
            </label>
           

            <button type="submit" class="btn-submit" style="margin-bottom:16px; margin-top: 0!important; ">Submit</button>
        </form>
    </div>
</div>

</div>
<script>
    function formSubmit(form){
        form.submit();    
    }
</script>
{% endblock content %}