admins/urls.py
from django.urls import path
from . import views
app_name = 'admins'

urlpatterns = [
    path('list/', views.showAdminsList, name='list'),
    path('detail/<int:id>/', views.getDetailOfAdmin, name='detail'),
    path('add/', views.showAdminForm, name='add'),
    path('edit/<int:id>/', views.showAdminForm, name='edit'),
    path('delete/<int:id>/', views.deleteAdmin, name='delete'),
    path('save/', views.saveAdmin, name='save'),
    path('checkDuplicate/', views.checkDuplicateUsernameAndEmployee,
         name='checkDuplicate'),
]

em_management/urls.py
from django.shortcuts import redirect
from django.urls import include, path
from admins.admin import admin_site
from . import views
from django.contrib.auth.views import (LoginView, LogoutView)


urlpatterns = [
    path('login/', LoginView.as_view(
        template_name='login.html',redirect_authenticated_user=True),name='login'),
    path('logout/',LogoutView.as_view(next_page='/login/'),name="logout"),
    path('home/', include('home.urls', namespace="home")),
    path('employees/', include('employees.urls', namespace="employees")),
    path('departments/', include('departments.urls', namespace="departments")),
    path('admins/', include('admins.urls', namespace="admins")),
    path('salaries/', include('salaries.urls', namespace="salaries")),
    path('', include("django.contrib.auth.urls")), 
    path('permission_error/', views.permission_error, name='permission_error'),
    path('', lambda request: redirect('/login/'), name='index'),
]

handler404="handle_error.views.handle_404"
handler500="handle_error.views.handle_500"

home/urls.py
from django.urls import path, include
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.showHome, name="home"),
]

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Employee Management</title>
    <link
      rel="shortcut icon"
      href="/static/image/logo/office.png"
      type="image/x-icon"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&family=Varela+Round&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    <link rel="stylesheet" href="{% static 'css/form.css' %}" />
    <link rel="stylesheet" href="{% static 'css/error.css' %}" />
    <link rel="stylesheet" href="{% static 'css/homepage.css' %}" />
    <script src="{% static 'js/main.js' %}"></script>
  </head>

  <body>
    <div class="container">
      <div class="side">
        <div class="title">
          <img src="{% static 'image/logo/office.png' %}" alt="" />
          <a href="{% url 'home:home' %}">
            <p>Management</p>
          </a>
        </div>
        <ul class="nav">
          <li class="nav-list">
            <i class="nav-icon fa-solid fa-users"></i>
            <p class="nav-text">
              <a href="{% url 'employees:list' %}">Employee</a>
            </p>
          </li>
          <li class="nav-list">
            <i class="nav-icon fa-solid fa-building-user"></i>
            <p class="nav-text">
              <a href="{% url 'departments:list' %}">Department</a>
            </p>
          </li>
          <li class="nav-list">
            <i class="nav-icon fa-solid fa-file-invoice-dollar"></i>
            <p class="nav-text">
              <a href="{% url 'salaries:list' %}">Salary Level</a>
            </p>
          </li>
          {% if user.is_superuser %}
          <li class="nav-list">
            <i class="nav-icon fa-solid fa-user"></i>
            <p class="nav-text"><a href="{% url 'admins:list' %}">Admin</a></p>
          </li>
          {% endif %}
        </ul>
        <div class="logout">
          <div class="btn-logout">
            <a href="/logout/">
              Log out
              <i class="fa-solid fa-right-from-bracket"></i>
            </a>
          </div>
        </div>
      </div>
      {% block content %} {% endblock content %}
    </div>
  </body>
</html>

templates/login.html
{% load static %} 

<html>
<head>
    <link rel="stylesheet" href="{% static 'css/login.css' %}" />
    <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
            integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"
    />
    <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossorigin="anonymous"
    />
    <title>Login</title>
</head>
<body>
<div class="container">
    <header class="header">
        <img class="logo" src="{% static 'image/logo/office.png' %}" alt="" />
        <h2 class="title">Management</h2>
    </header>
    <form name="login" class="form" action="{% url 'login' %}" method="post">
        {% csrf_token %}
        {% if form.errors %}
            <p style="color:#e63c3c; font-style: italic;">Your username or password is incorrect. Please try again.</p>
        {% endif %}
        <label for="username" class="label-username">
            <span class="username-span">Username</span>
            <div class="input-username-container">
                <i class="ph-envelope"></i>
                <input
                        type="text"
                        name="username"
                        id="username"
                        class="input-username"
                        placeholder="Enter your username"
                        autofocus
                        required
                />
            </div>
        </label>
        <label for="password" class="label-password">
            <span class="password-span">Password</span>

            <div class="input-password-container">
                <i class="ph-lock"></i>
                <input
                        type="password"
                        name="password"
                        id="password"
                        class="input-password"
                        placeholder="*************"
                        required
                />
            </div>
        </label>
        <button type="submit" class="btn-log-in">Login</button>
    </form>
</div>
</body>
</html>

templates/permission_error.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<div class="container">
<div class="error">
    <div class="error-info">
        <span>Permission error </span>
        <h2>The request page cannot be found.</h2>
        <h3>An error has occurred while processing your request.</h3>
        <h4>You may not be able to visit this page because of:</h4>
        <ul>
            <li>you have <strong>no access</strong> to this page (login to an manager's account to continue).</li>
        </ul>
        <a class="error-btn-homepage" href="{% url 'home:home' %}">Home page</a>
    </div>
    <div class="error-img">
        <img src="{% static 'image/error/404error.svg' %}" />
    </div>
</div>
</div>
{% endblock content %}